### ISSUE TITLE
[Feature] 소프트웨어학과 2학년 커리큘럼 트리 추가

### ISSUE THREAD

**Issue by soonitoon** [2021-opensw-project/CBNU-SW-curriculum#12]
## 설명

기존 CSS 스킬 트리를 소프트웨어학과 2학년 커리큘럼 트리로 변경합니다.

## Todo List

- [x] `src/data/fundamentals.js` 데이터 객체 중 CSS 부분 데이터 모두 2학년 커리큘럼 데이터로 수정.
    - [x] 1학기
        - [x] 자료구조
        - [x] 컴퓨터구조
        - [x] 소프트웨어실전영어
        - [x] 객체지향프로그래밍
        - [x] 선형대수학
        - [x] 미래설계구현
        - [x] 오픈소스기초프로젝트
    - [x] 2학기
        - [x] 알고리즘
        - [x] 프로그래밍언어론
        - [x] 시스템프로그래밍
        - [x] 창업탐색
        - [x] 오픈소스개발프로젝트
        - [x] 확률및통계
        - [x] 컴퓨터그래픽스
- [x] `assets/fundamentals/css` 디렉토리명 `2학년`으로 바꾸기.
- [x] `svg` 파일 이름 모두 과목명으로 수정.
