### ISSUE TITLE
[Feature] 소프트웨어학과 4학년 커리큘럼 트리 추가

### ISSUE THREAD

**Issue by chahyeonnaa** [2021-opensw-project/CBNU-SW-curriculum#18]
## 설명
기존 The Browser 스킬 트리를 소프트웨어학과 4학년 커리큘럼 트리로 변경합니다.
## Todo List

- [x] ```src/data/fundamentals.js``` 데이터 객체 중 The Browser 부분 데이터 모두 4학년 커리큘럼 데이터로 수정.
   - [x] 1학기
        - [x] 캡스톤디자인
        - [x] 임베디드시스템
        - [x] 영상처리
        - [x] 빅데이터시스템설계
        - [x] 기계학습
        - [x] 컴퓨터교재연구
        - [x] 창업산학세미나1
    - [x] 2학기
        - [x] 창업파일럿프로젝트
        - [x] 정보검색
        - [x] 자연어처리
        - [x] 빅데이터분석시각화
        - [x] 창업산학세미나2
        - [x] 컴퓨터교육론
        - [x] 클라우드컴퓨팅
- [x] ```assets/fundamentals/the-browser``` 부분 ```4학년```으로 바꾸기.
- [x] ```svg``` 파일 이름 모두 과목명으로 수정.
