### ISSUE TITLE
[Feature] 소프트웨어학과 1학년 커리큘럼 트리 추가

### ISSUE THREAD

**Issue by choheejin** [2021-opensw-project/CBNU-SW-curriculum#19]
## 설명
기존 HTML 스킬 트리를 소프트웨어학과 1학년 커리큘럼 트리로 변경합니다.

## Todo List

- [x] `src/data/fundamentals.js` 데이터 객체  HTML 부분 데이터 모두 1학년 커리큘럼 데이터로 수정
    - [x] 1학기
        - [x] 이산수학
        - [x] 창의공학설계
        - [x] 미래설계탐색
    - [x] 2학기
        - [x] 컴퓨터시스템개론
        - [x] 오픈소스소프트웨어이해와실습
        - [x] 미래설계준비
- [x] `assets/fundamentals/html` 디렉토리 명을  `assets/충북대-소프트웨어학과-커리큘럼/1학년`으로 변경
- [x] `svg` 파일 이름 모두 과목명으로 수정.
- [x] `src/data.js` 파일 수정
