### ISSUE TITLE
[Feature] 소프트웨어학과 3학년 커리큘럼 트리 추가 

### ISSUE THREAD

**Issue by parksanghyup** [2021-opensw-project/CBNU-SW-curriculum#23]
## 설명
기존 Javascript 스킬 트리를 소프트웨어학과 3학년 커리큘럼으로 변경합니다.
## Todo List

- [x] src/data/fundamenals.js 데이터 객체 중 Javascript 부분 데이터 모두 3학년 커리큘럼으로 변경 
    - [x] 1학기
        - [x] 운영체제
        - [x] 객체지향 설계
        - [x] 오픈소스 웹소프트웨어
        - [x] 컴파일러
        - [x] 컴퓨터 네트워크
        - [x] 창업기획
        - [x] 오픈소스 전문프로젝트
    - [x] 2학기
        - [x] 소프트웨어공학
        - [x] 산학프로젝트(종합설계)
        - [x] 펌웨어프로그래밍
        - [x] 창업설계
        - [x] 정보보호
        - [x] 인공지능
        - [x] 데이터베이스시스템 
- [x] assets/fundamentals/css 디렉토리명 2학년으로 바꾸기.
- [x] svg 파일명 소프트웨어 과목명으로 변경
